pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git 'https://github.com/oladip2080/Java-project1.git'
            }
        }
        stage('Build') {
            steps {
                sh 'cd MyWebApp && mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd MyWebApp mvn test'
                echo 'mvn test'
            }   
        }
        stage('Deploy to Tomcat') {
            steps {
                echo 'Last Stage'
                deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://18.118.209.42:8080/')], contextPath: 'path', war: '**/*.war'
            }
        }
    }
}
